name: Generate Snake Game from Contributions Grid

on:
  # Trigger the workflow daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Generate Snake Game
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          # GitHub username (dynamically set to repository owner)
          github_user_name: ${{ github.repository_owner }}

          # Specify the files and customization options for the outputs
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Commit and Push Snake Animation
      - name: Commit and Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*"
          message: "chore: update snake game animation"
          author_name: "GitHub Action"
          author_email: "github-action@users.noreply.github.com"
